/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import static Paneles.Panel_multiplayer.addgif;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Image;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import snakeandladders.Ventana_Registro;
import snakeandladders.Ventana_fichas;
import snakeandladders.Ventana_inicio;

/**
 *
 * @author Admin
 */
public class Panel_oneplayer extends javax.swing.JPanel {
    private TypingEffect typingEffect;
    private ImageIcon imagen;
    private Icon icono;
    /**
     * Creates new form Panel_login
     */
    public Panel_oneplayer() {
        initComponents();
        //fieldtext//
         // Hacer el JTextField transparente
        //TrabsparentButton    
        setTransparentBackground(txtnombre);
   
        setResizedImageIcon(LblTabla, "/Imagenes/Tabla.png");
        setResizedImageIcon(lblusername, "/Imagenes/username.png"); 
        setResizedImageIcon(lblusernameWrite, "/Imagenes/usernameWrite.png"); 
        setResizedImageIcon(lblfotoperfil, "/Imagenes/foto.png"); 
        setResizedImageIconForButton(btnlogin,"/Imagenes/login.png");
        setResizedImageIconForButton(btnregister,"/Imagenes/registrer.png");
        setResizedImageIcon(lblcheck, "/Imagenes/check.png");
        lblcheck.setVisible(false);
        setResizedImageIconForButton(btnback,"/Imagenes/back-button.png");
        addgif(lblpollito, "/Imagenes/pollito.gif"); 
        setResizedImageIcon(lblmensaje, "/Imagenes/comment.png"); 
        
        try {
            Font font = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/Fonts/Pixellari.ttf")); // Reemplaza "NombreDeTuFuente.ttf" con el nombre del archivo de tu fuente descargada
            font = font.deriveFont(Font.PLAIN, 17); // Cambia el tamaño de la fuente según tus necesidades
            MensajePollo.setFont(font);
            typingEffect = new TypingEffect(MensajePollo, "Ingrese el nombre del usuario", 7);
            typingEffect.start();
        } catch (FontFormatException | IOException ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        lblusernameWrite = new javax.swing.JLabel();
        lblfotoperfil = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblcheck = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnregister = new javax.swing.JButton();
        lblpollito = new javax.swing.JLabel();
        MensajePollo = new javax.swing.JLabel();
        lblmensaje = new javax.swing.JLabel();
        LblTabla = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Player Username ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 340, 40));

        lblusername.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jPanel1.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 510, 110));

        txtnombre.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(255, 255, 255));
        txtnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombre.setBorder(null);
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 350, 50));
        jPanel1.add(lblusernameWrite, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 500, 130));

        lblfotoperfil.setBackground(new java.awt.Color(0, 204, 0));
        lblfotoperfil.setForeground(new java.awt.Color(102, 255, 102));
        jPanel1.add(lblfotoperfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 160, 150));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("login");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 140, 40));
        jPanel1.add(lblcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 70, 70));

        btnlogin.setText("jButton1");
        btnlogin.setBorder(null);
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 360, 110));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Register");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 570, 190, 40));

        btnregister.setText("jButton1");
        btnregister.setBorder(null);
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 410, 130));
        jPanel1.add(lblpollito, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 190, 150));

        MensajePollo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MensajePollo.setText("Ingrese el nombre del usuario");
        jPanel1.add(MensajePollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 310, 80));

        lblmensaje.setText("jLabel1");
        jPanel1.add(lblmensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 430, 180));

        LblTabla.setText("jLabel1");
        jPanel1.add(LblTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 991, 686));

        btnback.setText("jButton1");
        btnback.setBorder(null);
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 170, 150));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1390, 720));
    }// </editor-fold>//GEN-END:initComponents

        //ResizedImagenIcon for JLabel
   private void setResizedImageIcon(JLabel label, String imagePath) {
    label.addComponentListener(new java.awt.event.ComponentAdapter() {
        public void componentResized(java.awt.event.ComponentEvent evt) {
            ImageIcon imagenIcono = new ImageIcon(getClass().getResource(imagePath));
            Image imagen = imagenIcono.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
            label.setIcon(new ImageIcon(imagen));
        }
    });
}
   
      
//ResizedImageIcon for button
private void setResizedImageIconForButton(JButton button, String imagePath) {
    button.addComponentListener(new java.awt.event.ComponentAdapter() {
        public void componentResized(java.awt.event.ComponentEvent evt) {
            ImageIcon imagenIcono = new ImageIcon(getClass().getResource(imagePath));
            Image imagen = imagenIcono.getImage().getScaledInstance(button.getWidth(), button.getHeight(), Image.SCALE_SMOOTH);
            button.setIcon(new ImageIcon(imagen));
            button.setBackground(new Color(0, 0, 0, 0));
        }
    });
}

   //setTransparentBackground
    private void setTransparentBackground(JComponent component) {
    component.setOpaque(false);
    component.setBackground(new Color(0, 0, 0, 0));
}

    
    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
       // Declaración de variables
    String usuario = txtnombre.getText();

    if (usuario.isEmpty()) {
        // Mostrar mensaje de error si falta ingresar el usuario
        typingEffect = new TypingEffect(MensajePollo, "Debes ingresar el nombre del usuario", 7);
        typingEffect.start();
    } else {
        try {
            Connection conexion = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PROYECTO_POO;TrustServerCertificate=True;",
                    "sa", "123456");
            String consulta = "SELECT COUNT(*) AS existe FROM USUARIO WHERE alias = ?";
            PreparedStatement sentencia = conexion.prepareStatement(consulta);
            sentencia.setString(1, usuario);
            ResultSet resultado = sentencia.executeQuery();

            if (resultado.next()) {
                int existe = resultado.getInt("existe");

                if (existe > 0) {
                    // Mostrar mensaje de inicio de sesión exitoso
                    typingEffect = new TypingEffect(MensajePollo, "Inicio de sesión exitoso", 7);
                    typingEffect.start();
                    Panel_ficha pf = new Panel_ficha();
                    pf.getGameMode(1);

                    // Hacer visible el lblcheck
                    lblcheck.setVisible(true);

                    JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
                    Ventana_fichas vf = new Ventana_fichas();
                    vf.setVisible(true);
                    frame.dispose();
                } else {
                    // Mostrar mensaje de usuario no registrado
                    typingEffect = new TypingEffect(MensajePollo, "El Usuario no está registrado", 7);
                    typingEffect.start();

                    // Ocultar el lblcheck
                    lblcheck.setVisible(false);
                }
            }

            resultado.close();
            sentencia.close();
            conexion.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        } catch (Exception e) {
            typingEffect = new TypingEffect(MensajePollo, "Necesita Ingresar el usuario", 7);
            typingEffect.start();

            System.out.println(e);
        }
    }

    }//GEN-LAST:event_btnloginActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed

        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this); // Obtiene la referencia al JFrame actual
        Ventana_Registro Va = new Ventana_Registro();
        Va.setVisible(true);
        frame.dispose(); // Cierra el JFrame actual
    }//GEN-LAST:event_btnregisterActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed

    JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this); // Obtiene la referencia al JFrame actual
        Ventana_inicio VI = new Ventana_inicio();
        
        VI.setVisible(true);
        frame.dispose(); // Cierra el JFrame actual
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblTabla;
    private javax.swing.JLabel MensajePollo;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnregister;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcheck;
    private javax.swing.JLabel lblfotoperfil;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JLabel lblpollito;
    private javax.swing.JLabel lblusername;
    private javax.swing.JLabel lblusernameWrite;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
