/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import snakeandladders.Ventana_inicio;

/**
 *
 * @author Admin
 */
public class Panel_about extends javax.swing.JPanel {

    /**
     * Creates new form Panel_about
     */
    public Panel_about() {
        initComponents();
        setResizedImageIcon(LblTabla, "/Imagenes/Tabla.png");
        setResizedImageIcon(lblboards1, "/Imagenes/boards.png");
        setResizedImageIcon(lblboards2, "/Imagenes/boards.png");
        setResizedImageIcon(lblboards3, "/Imagenes/boards.png");
        setResizedImageIcon(lblusername, "/Imagenes/username.png");
        setResizedImageIcon(lblgerman, "/Imagenes/german.jpg");
        setResizedImageIcon(lblmaria, "/Imagenes/maria.jpg");
        setResizedImageIcon(lbljosse, "/Imagenes/josse.jpg");
        setResizedImageIcon(lblgermanWrite, "/Imagenes/usernameWrite.png");
        setResizedImageIcon(lblmariaWrite, "/Imagenes/usernameWrite.png");
        setResizedImageIcon(lbljosseWrite, "/Imagenes/usernameWrite.png");
        setResizedImageIconForButton(btnback, "/Imagenes/back-button.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        lbljosse = new javax.swing.JLabel();
        lblboards3 = new javax.swing.JLabel();
        lblgerman = new javax.swing.JLabel();
        lblboards1 = new javax.swing.JLabel();
        lblmaria = new javax.swing.JLabel();
        lblboards2 = new javax.swing.JLabel();
        lbljosseWrite = new javax.swing.JLabel();
        lblgermanWrite = new javax.swing.JLabel();
        lblmariaWrite = new javax.swing.JLabel();
        LblTabla = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Register");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 570, 190, 40));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("     Maria");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 570, 190, 40));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("   German");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 190, 40));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                about");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 340, 40));

        lblusername.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jPanel1.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 510, 110));

        btnback.setText("jButton1");
        btnback.setBorder(null);
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 170, 150));

        lbljosse.setText("jLabel4");
        jPanel1.add(lbljosse, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, 190, 180));

        lblboards3.setText("jLabel1");
        jPanel1.add(lblboards3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 270, 310));

        lblgerman.setText("jLabel4");
        jPanel1.add(lblgerman, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 190, 180));

        lblboards1.setText("jLabel1");
        jPanel1.add(lblboards1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 270, 310));

        lblmaria.setText("jLabel4");
        jPanel1.add(lblmaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 190, 180));

        lblboards2.setText("jLabel1");
        jPanel1.add(lblboards2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 270, 310));
        jPanel1.add(lbljosseWrite, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 540, 240, 90));
        jPanel1.add(lblgermanWrite, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 240, 90));
        jPanel1.add(lblmariaWrite, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 240, 90));

        LblTabla.setText("jLabel1");
        jPanel1.add(LblTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 991, 686));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1390, 720));
    }// </editor-fold>//GEN-END:initComponents
    
    //ResizedImagenIcon for JLabel
    private void setResizedImageIcon(JLabel label, String imagePath) {
        label.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                ImageIcon imagenIcono = new ImageIcon(getClass().getResource(imagePath));
                Image imagen = imagenIcono.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
                label.setIcon(new ImageIcon(imagen));
            }
        });
    }
    
    //ResizedImageIcon for button
    private void setResizedImageIconForButton(JButton button, String imagePath) {
        button.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                ImageIcon imagenIcono = new ImageIcon(getClass().getResource(imagePath));
                Image imagen = imagenIcono.getImage().getScaledInstance(button.getWidth(), button.getHeight(), Image.SCALE_SMOOTH);
                button.setIcon(new ImageIcon(imagen));
                button.setBackground(new Color(0, 0, 0, 0));
            }
        });
    }
    
    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed

        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this); // Obtiene la referencia al JFrame actual
        Ventana_inicio Vi = new Ventana_inicio();

        Vi.setVisible(true);
        frame.dispose(); // Cierra el JFrame actual
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblTabla;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblboards1;
    private javax.swing.JLabel lblboards2;
    private javax.swing.JLabel lblboards3;
    private javax.swing.JLabel lblgerman;
    private javax.swing.JLabel lblgermanWrite;
    private javax.swing.JLabel lbljosse;
    private javax.swing.JLabel lbljosseWrite;
    private javax.swing.JLabel lblmaria;
    private javax.swing.JLabel lblmariaWrite;
    private javax.swing.JLabel lblusername;
    // End of variables declaration//GEN-END:variables
}
