/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import snakeandladders.Ventana_About;
import snakeandladders.Ventana_ladeboard;
import snakeandladders.Ventana_multiplayer;
import snakeandladders.Ventanan_oneplayer;

/**
 *
 * @author JOSE
 */
public class Panel_inicio extends javax.swing.JPanel {

    /**
     * Creates new form Panel_inicio
     */
    public Panel_inicio() {
        initComponents();
        
    //setResizedImageIcon(LblTabla, "/Imagenes/Tabla.png");
    setResizedImageIcon(lblmiau, "/Imagenes/miau.png");
    setResizedImageIconForButton(btnone_player,"/Imagenes/oneplayer.png");
    setResizedImageIconForButton(btnmultiplayer,"/Imagenes/multiplayer.png");
    setResizedImageIconForButton(btnleaders,"/Imagenes/leaders.png");
    setResizedImageIconForButton(btnbinfo,"/Imagenes/incognito.png");
    setResizedImageIconForButton(btnsexit,"/Imagenes/exit.png");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblmiau = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnleaders = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnone_player = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnmultiplayer = new javax.swing.JButton();
        btnsexit = new javax.swing.JButton();
        btnbinfo = new javax.swing.JButton();

        setOpaque(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblmiau.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jPanel1.add(lblmiau, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 90, 80));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 80)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LADDERS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 410, 100));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 80)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SNAKE AND ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 450, 130));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("leaders");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, 230, 60));

        btnleaders.setText("jButton3");
        btnleaders.setBorder(null);
        btnleaders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnleadersActionPerformed(evt);
            }
        });
        jPanel1.add(btnleaders, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 530, 100));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("one player");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 350, 70));

        btnone_player.setText("jButton1");
        btnone_player.setBorder(null);
        btnone_player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnone_playerActionPerformed(evt);
            }
        });
        jPanel1.add(btnone_player, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 530, 100));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("multiplayer");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 380, 60));

        btnmultiplayer.setText("jButton2");
        btnmultiplayer.setBorder(null);
        btnmultiplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiplayerActionPerformed(evt);
            }
        });
        jPanel1.add(btnmultiplayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 660, 100));

        btnsexit.setText("jButton1");
        btnsexit.setBorder(null);
        btnsexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnsexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 200, 200));

        btnbinfo.setText("jButton2");
        btnbinfo.setBorder(null);
        btnbinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbinfoActionPerformed(evt);
            }
        });
        jPanel1.add(btnbinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 540, 160, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnleadersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnleadersActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this); // Obtiene la referencia al JFrame actual
        Ventana_ladeboard Va = new Ventana_ladeboard ();
        Va.setVisible(true);
        frame.dispose(); // Cierra el JFrame actua
    }//GEN-LAST:event_btnleadersActionPerformed

    private void btnone_playerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnone_playerActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this); // Obtiene la referencia al JFrame actual
        Ventanan_oneplayer Va = new Ventanan_oneplayer();
        Va.setVisible(true);
        frame.dispose(); // Cierra el JFrame actua
    }//GEN-LAST:event_btnone_playerActionPerformed

    private void btnmultiplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiplayerActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this); // Obtiene la referencia al JFrame actual
        Ventana_multiplayer Va = new Ventana_multiplayer();
        Va.setVisible(true);
        frame.dispose(); // Cierra el JFrame actua
    }//GEN-LAST:event_btnmultiplayerActionPerformed

    private void btnsexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsexitActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose();
    }//GEN-LAST:event_btnsexitActionPerformed

    private void btnbinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbinfoActionPerformed
         JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this); 
        Ventana_About VA = new Ventana_About();
        VA.setVisible(true);
        frame.dispose(); 
    }//GEN-LAST:event_btnbinfoActionPerformed
    
    //ResizedImagenIcon for JLabel
   private void setResizedImageIcon(JLabel label, String imagePath) {
    label.addComponentListener(new java.awt.event.ComponentAdapter() {
        public void componentResized(java.awt.event.ComponentEvent evt) {
            ImageIcon imagenIcono = new ImageIcon(getClass().getResource(imagePath));
            Image imagen = imagenIcono.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
            label.setIcon(new ImageIcon(imagen));
        }
    });
}
   
   //ResizedImageIcon for button
private void setResizedImageIconForButton(JButton button, String imagePath) {
    button.addComponentListener(new java.awt.event.ComponentAdapter() {
        public void componentResized(java.awt.event.ComponentEvent evt) {
            ImageIcon imagenIcono = new ImageIcon(getClass().getResource(imagePath));
            Image imagen = imagenIcono.getImage().getScaledInstance(button.getWidth(), button.getHeight(), Image.SCALE_SMOOTH);
            button.setIcon(new ImageIcon(imagen));
            button.setBackground(new Color(0, 0, 0, 0));
        }
    });
}
    
    //setTransparentBackground
    private void setTransparentBackground(JComponent component) {
    component.setOpaque(false);
    component.setBackground(new Color(0, 0, 0, 0));
}

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbinfo;
    private javax.swing.JButton btnleaders;
    private javax.swing.JButton btnmultiplayer;
    private javax.swing.JButton btnone_player;
    private javax.swing.JButton btnsexit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblmiau;
    // End of variables declaration//GEN-END:variables
}
