/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Image;
import java.io.IOException;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import snakeandladders.Ventana_inicio;

/**
 *
 * @author Admin
 */
public class Panel_registro extends javax.swing.JPanel {

    private String sexselected;
    private TypingEffect typingEffect;

    /**
     * Creates new form Panel_registro
     */
    public Panel_registro() {
        initComponents();
        //TrabsparentButton    
        setTransparentBackground(txtnombre);
        setTransparentBackground(txtusername);
        setTransparentBackground(txtage);
        //setTransparentBackground(txtsex);

        //ResizedImage
        setResizedImageIcon(LblTabla, "/Imagenes/Tabla.png");
        setResizedImageIconForButton(btnregister, "/Imagenes/registrer.png");
        setResizedImageIcon(lblname, "/Imagenes/username.png");
        setResizedImageIcon(lblnameWrite, "/Imagenes/usernameWrite.png");
        setResizedImageIcon(lblusername, "/Imagenes/username.png");
        setResizedImageIcon(lblusernameWrite, "/Imagenes/usernameWrite.png");
        setResizedImageIcon(lblsex, "/Imagenes/username.png");
        setResizedImageIcon(lblsexWrite1, "/Imagenes/malewithout.png");
        setResizedImageIcon(lblsexWrite1_1, "/Imagenes/malewith.png");
        setResizedImageIcon(lblsexWrite2, "/Imagenes/femalewithout.png");
        setResizedImageIcon(lblsexWrite_2, "/Imagenes/femalewith.png");
        setResizedImageIcon(lblage, "/Imagenes/username.png");
        setResizedImageIcon(lblageWriter, "/Imagenes/usernameWrite.png");
        setResizedImageIconForButton(btnsubmit, "/Imagenes/login.png");
        setResizedImageIcon(lblcheck, "/Imagenes/check.png");
        lblcheck.setVisible(false);
        setResizedImageIconForButton(btnback, "/Imagenes/back-button.png");
        addgif(lblpollito, "/Imagenes/pollito_1.gif");
        setResizedImageIcon(lblmensaje, "/Imagenes/comment.png");

        try {
            Font font = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/Fonts/Pixellari.ttf")); // Reemplaza "NombreDeTuFuente.ttf" con el nombre del archivo de tu fuente descargada
            font = font.deriveFont(Font.PLAIN, 17); // Cambia el tamaño de la fuente según tus necesidades
            MensajePollo.setFont(font);
            typingEffect = new TypingEffect(MensajePollo, "Ingrese el nombre del usuario", 7);
            typingEffect.start();
        } catch (FontFormatException | IOException ex) {
            ex.printStackTrace();

        }

        // Agregar ActionListener a lblsexWrite1
        lblsexWrite1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsexWrite1MouseClicked(evt);
            }
        });

        // Agregar ActionListener a lblsexWriter
        lblsexWrite2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsexWrite2MouseClicked(evt);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblcheck = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        lblnameWrite = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnregister = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        lblusernameWrite = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblsex = new javax.swing.JLabel();
        lblsexWrite2 = new javax.swing.JLabel();
        lblsexWrite_2 = new javax.swing.JLabel();
        lblsexWrite1 = new javax.swing.JLabel();
        lblsexWrite1_1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        lblageWriter = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        MensajePollo = new javax.swing.JLabel();
        lblmensaje = new javax.swing.JLabel();
        lblpollito = new javax.swing.JLabel();
        LblTabla = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lblcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 590, 70, 70));

        txtnombre.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(255, 255, 255));
        txtnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombre.setBorder(null);
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 420, 50));
        jPanel1.add(lblnameWrite, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 510, 90));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("submit");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 610, 140, 40));

        btnsubmit.setText("jButton1");
        btnsubmit.setBorder(null);
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 570, 360, 110));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Register");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 190, 40));

        btnregister.setText("jButton1");
        btnregister.setBorder(null);
        jPanel1.add(btnregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 410, 130));

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 140, 40));

        lblname.setText("jLabel1");
        jPanel1.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 340, 90));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("UsernAME:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 210, 40));

        lblusername.setText("jLabel1");
        jPanel1.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 340, 90));

        txtusername.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtusername.setBorder(null);
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 420, 50));
        jPanel1.add(lblusernameWrite, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 510, 90));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SEX:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 90, 40));

        lblsex.setText("jLabel1");
        jPanel1.add(lblsex, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 340, 90));
        jPanel1.add(lblsexWrite2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 370, 210, 90));
        jPanel1.add(lblsexWrite_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 370, 210, 90));
        jPanel1.add(lblsexWrite1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 210, 90));
        jPanel1.add(lblsexWrite1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 210, 90));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Age:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 90, 40));

        lblage.setText("jLabel1");
        jPanel1.add(lblage, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 340, 90));

        txtage.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        txtage.setForeground(new java.awt.Color(255, 255, 255));
        txtage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtage.setBorder(null);
        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });
        jPanel1.add(txtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 420, 50));
        jPanel1.add(lblageWriter, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, 510, 90));

        btnback.setText("jButton1");
        btnback.setBorder(null);
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 170, 150));

        MensajePollo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MensajePollo.setText("Ingrese el nombre del usuario");
        jPanel1.add(MensajePollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 570, 310, 80));

        lblmensaje.setText("jLabel1");
        jPanel1.add(lblmensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 550, 440, 180));
        jPanel1.add(lblpollito, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 600, 210, 170));

        LblTabla.setText("jLabel1");
        jPanel1.add(LblTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 991, 686));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1470, 850));
    }// </editor-fold>//GEN-END:initComponents

    //ResizedImagenIcon for JLabel
    private void setResizedImageIcon(JLabel label, String imagePath) {
        label.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                ImageIcon imagenIcono = new ImageIcon(getClass().getResource(imagePath));
                Image imagen = imagenIcono.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
                label.setIcon(new ImageIcon(imagen));
            }
        });
    }

    public static void addgif(JLabel label, String rutaImagen) {
        label.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                ImageIcon imagenIcono = new ImageIcon(getClass().getResource(rutaImagen));
                Image imagen = imagenIcono.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_DEFAULT);
                ImageIcon icono = new ImageIcon(imagen);
                label.setIcon(icono);
            }
        });
    }

// ActionListener para lblsexWrite1
    private void lblsexWrite1MouseClicked(java.awt.event.MouseEvent evt) {
        lblsexWrite1.setVisible(false);  // Ocultar lblsexWrite1
        lblsexWrite1_1.setVisible(true);   // Mostrar lblsexWriter
        lblsexWrite2.setVisible(true);   // Mostrar lblsexWriter
        lblsexWrite_2.setVisible(false);  // Ocultar lblsexWrite1

        sexselected = "Male";

    }

// ActionListener para lblsexWriter
    private void lblsexWrite2MouseClicked(java.awt.event.MouseEvent evt) {
        lblsexWrite2.setVisible(false);   // Mostrar lblsexWrite1
        lblsexWrite_2.setVisible(true);  // Ocultar lblsexWriter
        lblsexWrite1.setVisible(true);  // Ocultar lblsexWrite1
        lblsexWrite1_1.setVisible(false);   // Mostrar lblsexWriter

        sexselected = "Female";
    }

//ResizedImageIcon for button
    private void setResizedImageIconForButton(JButton button, String imagePath) {
        button.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                ImageIcon imagenIcono = new ImageIcon(getClass().getResource(imagePath));
                Image imagen = imagenIcono.getImage().getScaledInstance(button.getWidth(), button.getHeight(), Image.SCALE_SMOOTH);
                button.setIcon(new ImageIcon(imagen));
                button.setBackground(new Color(0, 0, 0, 0));
            }
        });
    }

    //setTransparentBackground
    private void setTransparentBackground(JComponent component) {
        component.setOpaque(false);
        component.setBackground(new Color(0, 0, 0, 0));
    }

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        String sex = "";
        if (sexselected != null) {
            if (sexselected.equals("Male")) {
                sex = "Male";
            } else if (sexselected.equals("Female")) {
                sex = "Female";
            }

            String name = txtnombre.getText();
            String username = txtusername.getText();
            int age = Integer.parseInt(txtage.getText());

            if (name.isEmpty() || username.isEmpty() || age <= 0) {
              //  JOptionPane.showMessageDialog(null, "No puede ingresar valores negativos");
                typingEffect = new TypingEffect(MensajePollo, "No pueden ingresar valores negativos", 7);
                typingEffect.start();
                return;
            }

            // Validar nombre de usuario y longitud
            if (username.length() >= 15 || name.length()>= 15 ) {
                //JOptionPane.showMessageDialog(null, "El nombre de usuario debe tener como máximo 15 caracteres.");
                typingEffect = new TypingEffect(MensajePollo, "Debe tener como máximo 15 caracteres", 7);
                typingEffect.start();
                return;
            }else if(age !=2){
                 typingEffect = new TypingEffect(MensajePollo, "Ingrese una edad valida", 7);
                typingEffect.start();
                return;
            }

            // Verificar si el nombre de usuario ya existe
            try {
                Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PROYECTO_POO;TrustServerCertificate=True;", "sa", "123456");
                String consulta = "SELECT COUNT(*) FROM USUARIO WHERE alias = ?";
                PreparedStatement statementCheck = connection.prepareStatement(consulta);
                statementCheck.setString(1, username);
                ResultSet resultSet = statementCheck.executeQuery();
                resultSet.next();
                int count = resultSet.getInt(1);
                if (count > 0) {
                   // JOptionPane.showMessageDialog(null, "El nombre de usuario ya está en uso. Por favor, elija otro.");
                   typingEffect = new TypingEffect(MensajePollo, "Elija otro usuario ese ya esta registrado", 7);
                   typingEffect.start();
                
                   

                    resultSet.close();
                    statementCheck.close();
                    connection.close();
                    return;
                } else {
                    // JOptionPane.showMessageDialog(null, "Usuario no está registrado");
                    typingEffect = new TypingEffect(MensajePollo, "El Usuario no está registrado", 7);
                    typingEffect.start();

                    // Ocultar el lblcheck
                    lblcheck.setVisible(false);
                    
                }
                resultSet.close();
                statementCheck.close();

                // Inserción en la base de datos
                String consultainsert = "INSERT INTO USUARIO(nombre, alias, sexo, edad) VALUES (?, ?, ?, ?)";
                PreparedStatement statement = connection.prepareStatement(consultainsert);
                statement.setString(1, name);
                statement.setString(2, username);
                statement.setString(3, sex);
                statement.setInt(4, age);
                statement.executeUpdate();
                statement.close();
                //JOptionPane.showMessageDialog(this, "Registro agregado exitosamente");
                typingEffect = new TypingEffect(MensajePollo, "Registro agregado exitosamente", 7);
                typingEffect.start();

                // Hacer visible el lblcheck
                lblcheck.setVisible(true);

                connection.close();
            } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(this, "Error al agregar el registro: " + ex.getMessage());
                typingEffect = new TypingEffect(MensajePollo, "Error al agregar el registro", 7);
                typingEffect.start();
            }
        }

    }//GEN-LAST:event_btnsubmitActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtageActionPerformed
//    int ventana1 = -1;
//    
//    public void setback(int num){
//        ventana1 = num;
//        
//    }

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        Ventana_inicio VI = new Ventana_inicio();

        VI.setVisible(true);
        frame.dispose();


    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblTabla;
    private javax.swing.JLabel MensajePollo;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnregister;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblageWriter;
    private javax.swing.JLabel lblcheck;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblnameWrite;
    private javax.swing.JLabel lblpollito;
    private javax.swing.JLabel lblsex;
    private javax.swing.JLabel lblsexWrite1;
    private javax.swing.JLabel lblsexWrite1_1;
    private javax.swing.JLabel lblsexWrite2;
    private javax.swing.JLabel lblsexWrite_2;
    private javax.swing.JLabel lblusername;
    private javax.swing.JLabel lblusernameWrite;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
